### ISSUE TITLE
프레임웍 yes 순 정렬시 reload 되면 좋을 거 같음

### ISSUE THREAD

**Issue by chaeeewon** [chaeeewon/classifier#3]
yes 순으로 정렬한 페이지에서 해당 페이지에 떠있는 이미지들 레이블링 후 다음 애들이 자동으로 떴으면 좋겠어요! 지금은 yes 순 정렬 메뉴 다시 눌러서 새로고침하면서 했어요!

**Comment by paryoja** [comment]
반영 완료 했습니다
