### ISSUE TITLE
[UI/UX]분류된 이미지가 적은 순으로 추가 분류할 수 있는 UI가 있으면 좋겠어요

### ISSUE THREAD

**Issue by chaeeewon** [chaeeewon/classifier#6]
지금 이미지가 부족한 포켓몬을 추가로 라벨링하고 싶으면 
📍 1. [결과 -> 분류현황]을 보고 이미지가 부족한 포켓몬 발견 
📍 2. [ 분류 -> 남은 이미지 현황]에 들어가서 
📍 3. ctrl+F로 포켓몬 이름을 치고 들어가서 라벨링

이런 식으로 해야 하는데, 이 과정이 복잡해서 개선되면 좋을 것 같습니다! 🎉 

🔥 제안 1. [결과 -> 분류현황]이 지금 이미지가 적은 순으로 소팅되어있으므로 옆에 [분류하러 가기] 버튼 만들기

🔥 제안 2. [분류 -> 남은 이미지 현황] 페이지가 불필요해보이니 이 페이지를 다른 용도로 바꾸기
(우리에게 필요한 정보는 쓸모 있는 이미지가 몇개인지 >>> 아직 라벨링 안된 이미지가 몇개인지 이므로)

**Comment by paryoja** [comment]
수정했습니다.
UX 담당자가 필요합니다 ㅋㅋ
